In [4]:
import os

notebookPath = os.path.dirname(os.getcwd())

In [1]:
import scanpy as sc
adata = sc.read("/mnt/SATA/spatialCourse/outputIntegrated/spatialPaperFiltered.h5ad")

In [2]:
adata.layers["counts"] = adata.X.copy()

In [3]:
sc.experimental.pp.normalize_pearson_residuals(adata)

sc.pp.highly_variable_genes(
    adata,
    flavor="seurat_v3",
    n_top_genes=5000,
    batch_key="library_id",
    layer="counts",
    subset=False
)
sc.pp.scale(adata)

In [5]:
bdata = sc.read(os.path.join(notebookPath, "outputIntegrated", "output.scviAnndataTrained.h5ad"))

In [6]:
bdata.obsm["X_scVI"]

array([[ 1.1851457 , -0.37805098,  1.1134106 , ...,  1.4091347 ,
        -1.3358011 , -0.22238785],
       [ 1.5716149 ,  1.3046604 , -2.9951742 , ...,  0.32769948,
        -0.9727162 ,  0.53829074],
       [-0.08083832,  0.25731358,  1.742876  , ..., -1.0038364 ,
        -0.49267742, -1.2243924 ],
       ...,
       [ 0.74401915, -0.14600535,  0.8684896 , ..., -1.5547453 ,
        -0.5358968 , -1.1648831 ],
       [ 1.4379691 , -1.2182065 , -1.0298202 , ...,  0.9942666 ,
        -0.08652391, -0.20098126],
       [ 1.0833519 , -1.2475553 , -1.0170786 , ...,  1.257415  ,
         0.7768904 , -0.1347273 ]], dtype=float32)

In [7]:
bdata.obs

,array_row,array_col,n_genes_by_counts,log1p_n_genes_by_counts,total_counts,log1p_total_counts,pct_counts_in_top_50_genes,pct_counts_in_top_100_genes,pct_counts_in_top_200_genes,pct_counts_in_top_500_genes,...,leiden_0_8,leiden_0_9,leiden_1_0,leiden_1_1,leiden_1_2,leiden_1_3,leiden_1_4,leiden_0.6,leiden_0.7,leiden_0.8
AAACAATCTACTAGCA-1,3,43,2021,7.611842,4906.0,8.498418,37.280881,46.127191,54.912352,68.304117,...,0,0,0,0,0,0,0,0,0,0
AAACCGGGTAGGTACC-1,42,28,6407,8.765302,20087.0,9.907878,16.055160,23.308608,32.219844,44.909643,...,1,1,1,1,1,1,1,1,1,1
AAACCGTTCGTCCAGG-1,52,42,3140,8.052296,8603.0,9.059982,37.347437,44.159014,51.958619,63.535976,...,2,2,2,2,2,2,2,2,2,2
AAACCTCATGAAGTTG-1,37,19,4518,8.416046,12775.0,9.455323,30.896282,38.230920,45.831703,56.743640,...,3,3,3,3,3,3,3,3,3,3
AAACGAAGAACATACC-1,6,64,3170,8.061802,12449.0,9.429476,53.843682,59.627279,66.005302,74.520042,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTGTTCAGTGTGCTAC-1-3,24,64,3810,8.245647,9951.0,9.205529,20.259270,29.414129,39.222189,53.944327,...,10,13,11,19,14,22,15,7,9,7
TTGTTGTGTGTCAAGA-1-3,31,77,3708,8.218518,9806.0,9.190852,20.997349,29.583928,40.026514,55.007138,...,2,19,13,16,17,19,29,6,7,6
TTGTTTCACATCCAGG-1-2,58,42,2177,7.686162,4773.0,8.470940,23.968154,33.563796,44.688875,60.946994,...,0,0,0,0,0,20,16,0,0,0
TTGTTTCATTAGTCTA-1-1,60,30,3157,8.057694,8402.0,9.036345,24.815520,35.265413,45.739110,59.569150,...,16,11,10,23,23,25,28,9,12,9
TTGTTTGTATTACACG-1,73,41,4842,8.485290,15893.0,9.673697,22.720695,31.869376,41.471088,55.326244,...,14,11,10,13,19,18,26,9,11,9

In [21]:
# adata = adata[adata.obs.index.isin(bdata.obs.index)]

In [8]:
adata.obsm["X_scVI"] = bdata.obsm["X_scVI"].copy()
adata.obsm["X_umap"] = bdata.obsm["X_umap"].copy()

In [10]:
import spatools as st

adata.var["gene_ids"] = adata.var.index

st.tl.translate_anndata_genes(adata, col = "gene_ids")

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed
6 input query terms found dup hits:	[('ENSG00000261600', 2), ('ENSG00000227110', 2), ('ENSG00000175711', 2), ('ENSG00000280018', 2), ('E
221 input query terms found no hit:	['ENSG00000238009', 'ENSG00000271895', 'ENSG00000226849', 'ENSG00000272482', 'ENSG00000261135', 'ENS

AnnData object with n_obs × n_vars = 11219 × 18594
    obs: 'array_row', 'array_col', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'library_id'
    var: 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm', 'highly_variable_nbatches', 'mean', 'std', 'gene_ids', 'gene_symbol'
    uns: 'preprocessing_stats_FB_P1_S2', 'preprocessing_stats_FB_P26_S4', 'preprocessing_stats_UB_P10_S2', 'preprocessing_stats_UB_P25_S4', 'spatial', 'pearson_residuals_normalization', 'hvg'
    obsm: 'spatial', 'X_scVI', 'X_umap'
    layers: 'counts'

In [11]:
print(f"ENS: {len([i for i in adata.var.index if i.startswith('ENS')])}")
print(f"Symbols: {len([i for i in adata.var.index if not i.startswith('ENS')])}")

ENS: 1379
Symbols: 17215

In [12]:
adata.var

,highly_variable,highly_variable_rank,means,variances,variances_norm,highly_variable_nbatches,mean,std,gene_ids,gene_symbol
ENSG00000238009,False,NaN,0.004992,0.005145,0.978098,0,-0.002701,0.960940,ENSG00000238009,ENSG00000238009
LINC01409,True,1345.0,0.060166,0.068674,1.013085,1,-0.008646,1.003761,ENSG00000237491,LINC01409
LINC00115,False,3755.0,0.007755,0.007874,0.973596,1,0.005144,1.071342,ENSG00000225880,LINC00115
FAM41C,False,3442.0,0.047509,0.057379,0.995471,2,0.000128,1.061024,ENSG00000230368,FAM41C
LINC02593,False,3202.0,0.017470,0.018950,0.981846,1,-0.002358,1.007128,ENSG00000223764,LINC02593
...,...,...,...,...,...,...,...,...,...,...
MAFIP,False,3927.0,0.030841,0.032745,0.967957,1,-0.019873,0.872267,ENSG00000274847,MAFIP
ENSG00000276256,False,2634.0,0.037258,0.040330,1.002033,1,-0.010240,0.964317,ENSG00000276256,ENSG00000276256
ENSG00000273748,False,2985.0,0.008913,0.009548,0.998737,1,-0.006526,0.938833,ENSG00000273748,ENSG00000273748
ENSG00000278817,True,1468.0,0.044032,0.049942,0.985959,1,0.014432,1.122262,ENSG00000278817,ENSG00000278817
LOC124905564,False,NaN,0.004992,0.004967,0.962781,0,0.010244,1.132321,ENSG00000271254,LOC124905564

In [13]:
adata.obs_names_make_unique()
sc.write(filename=os.path.join(notebookPath, "outputIntegrated", "spatialPaper_full_genes.h5ad"), adata=adata)