In [15]:
import scanpy as sc
adata = sc.read("/mnt/SATA/spatialCourse/outputIntegrated/spatialPaperFiltered.h5ad")

In [16]:
adata.layers["counts"] = adata.X.copy()

In [17]:
sc.experimental.pp.normalize_pearson_residuals(adata)

sc.pp.highly_variable_genes(
    adata,
    flavor="seurat_v3",
    n_top_genes=5000,
    batch_key="library_id",
    layer="counts",
    subset=False
)
sc.pp.scale(adata)

In [18]:
bdata = sc.read("/mnt/SATA/spatialCourse/outputIntegrated/output.scviAnndataTrained.h5ad")

In [19]:
bdata.obsm["X_scVI"]

array([[ 0.5843022 ,  0.21313179, -0.6747159 , ...,  0.65441656,
        -0.43109775, -1.6105375 ],
       [-0.08688232, -1.4406255 ,  0.741925  , ..., -1.293208  ,
        -1.5684842 ,  0.46255064],
       [-0.9368518 ,  0.9429644 , -0.1529143 , ..., -0.6746143 ,
        -0.7072993 , -0.66017354],
       ...,
       [ 0.38832822,  0.90207696, -1.9285438 , ...,  0.90323955,
         0.6521986 , -0.13237894],
       [-0.17718706,  0.7050808 , -0.7466201 , ..., -1.4533411 ,
        -0.15359925, -0.59394956],
       [ 0.25158322,  1.2153817 , -0.13349453, ..., -1.7871789 ,
        -0.92827564, -0.6744373 ]], dtype=float32)

In [20]:
bdata.obs

,array_row,array_col,n_genes_by_counts,log1p_n_genes_by_counts,total_counts,log1p_total_counts,pct_counts_in_top_50_genes,pct_counts_in_top_100_genes,pct_counts_in_top_200_genes,pct_counts_in_top_500_genes,total_counts_mt,log1p_total_counts_mt,pct_counts_mt,library_id,response,study,_scvi_batch,_scvi_labels,leiden_0.5
AAACAATCTACTAGCA-1,3,43,2021,7.611842,4906.0,8.498418,37.280881,46.127191,54.912352,68.304117,173.0,5.159055,3.526294,FB_P1_S2,FB,S2,0,0,0
AAACCGGGTAGGTACC-1,42,28,6407,8.765302,20087.0,9.907878,16.055160,23.308608,32.219844,44.909643,435.0,6.077642,2.165580,FB_P1_S2,FB,S2,0,0,1
AAACCGTTCGTCCAGG-1,52,42,3140,8.052296,8603.0,9.059982,37.347437,44.159014,51.958619,63.535976,202.0,5.313206,2.348018,FB_P1_S2,FB,S2,0,0,2
AAACCTCATGAAGTTG-1,37,19,4518,8.416046,12775.0,9.455323,30.896282,38.230920,45.831703,56.743640,1260.0,7.139660,9.863014,FB_P1_S2,FB,S2,0,0,3
AAACGAAGAACATACC-1,6,64,3170,8.061802,12449.0,9.429476,53.843682,59.627279,66.005302,74.520042,182.0,5.209486,1.461965,FB_P1_S2,FB,S2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTGTTCAGTGTGCTAC-1-3,24,64,3810,8.245647,9951.0,9.205529,20.259270,29.414129,39.222189,53.944327,148.0,5.003946,1.487288,UB_P25_S4,UB,S4,1,0,1
TTGTTGTGTGTCAAGA-1-3,31,77,3708,8.218518,9806.0,9.190852,20.997349,29.583928,40.026514,55.007138,195.0,5.278115,1.988578,UB_P25_S4,UB,S4,1,0,6
TTGTTTCACATCCAGG-1-2,58,42,2177,7.686162,4773.0,8.470940,23.968154,33.563796,44.688875,60.946994,128.0,4.859812,2.681751,UB_P25_S4,UB,S4,1,0,3
TTGTTTCATTAGTCTA-1-1,60,30,3157,8.057694,8402.0,9.036345,24.815520,35.265413,45.739110,59.569150,133.0,4.897840,1.582957,UB_P25_S4,UB,S4,1,0,5
TTGTTTGTATTACACG-1,73,41,4842,8.485290,15893.0,9.673697,22.720695,31.869376,41.471088,55.326244,92.0,4.532599,0.578871,UB_P25_S4,UB,S4,1,0,5

In [21]:
# adata = adata[adata.obs.index.isin(bdata.obs.index)]

In [22]:
adata.obsm["X_scVI"] = bdata.obsm["X_scVI"].copy()
adata.obsm["X_umap"] = bdata.obsm["X_umap"].copy()

In [ ]:
import spatools as st

adata.var["gene_ids"] = adata.index

st.tl.translate_anndata_genes(adata, col = "gene_ids")

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed
17437 input query terms found no hit:	['ENSG00000238009', 'LINC01409', 'LINC00115', 'FAM41C', 'LINC02593', 'SAMD11', 'NOC2L', 'KLHL17', 'P

AnnData object with n_obs × n_vars = 11219 × 18594
    obs: 'array_row', 'array_col', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'library_id'
    var: 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm', 'highly_variable_nbatches', 'mean', 'std', 'gene_ids', 'gene_symbol'
    uns: 'preprocessing_stats_FB_P1_S2', 'preprocessing_stats_FB_P26_S4', 'preprocessing_stats_UB_P10_S2', 'preprocessing_stats_UB_P25_S4', 'spatial', 'pearson_residuals_normalization', 'hvg'
    obsm: 'spatial', 'X_scVI', 'X_umap'
    layers: 'counts'

In [33]:
print(f"ENS: {len([i for i in adata.var.index if i.startswith('ENS')])}")
print(f"Symbols: {len([i for i in adata.var.index if not i.startswith('ENS')])}")

ENS: 1379
Symbols: 17215

In [34]:
adata.var

,highly_variable,highly_variable_rank,means,variances,variances_norm,highly_variable_nbatches,mean,std,gene_ids,gene_symbol
ENSG00000238009,False,NaN,0.004992,0.005145,0.978098,0,-0.002701,0.960940,ENSG00000238009,ENSG00000238009
LINC01409,True,1345.0,0.060166,0.068674,1.013085,1,-0.008646,1.003761,LINC01409,LINC01409
LINC00115,False,3755.0,0.007755,0.007874,0.973596,1,0.005144,1.071342,LINC00115,LINC00115
FAM41C,False,3442.0,0.047509,0.057379,0.995471,2,0.000128,1.061024,FAM41C,FAM41C
LINC02593,False,3202.0,0.017470,0.018950,0.981846,1,-0.002358,1.007128,LINC02593,LINC02593
...,...,...,...,...,...,...,...,...,...,...
MAFIP,False,3927.0,0.030841,0.032745,0.967957,1,-0.019873,0.872267,MAFIP,MAFIP
ENSG00000276256,False,2634.0,0.037258,0.040330,1.002033,1,-0.010240,0.964317,ENSG00000276256,ENSG00000276256
ENSG00000273748,False,2985.0,0.008913,0.009548,0.998737,1,-0.006526,0.938833,ENSG00000273748,ENSG00000273748
ENSG00000278817,True,1468.0,0.044032,0.049942,0.985959,1,0.014432,1.122262,ENSG00000278817,ENSG00000278817
LOC124905564,False,NaN,0.004992,0.004967,0.962781,0,0.010244,1.132321,LOC124905564,LOC124905564

In [28]:
adata.obs_names_make_unique()
sc.write("/mnt/SATA/spatialCourse/outputIntegrated/spatialPaper_full_genes.h5ad", adata)